export const addressList: string[] = [
  "전체",
  "서울",
  "경기",
  "강원",
  "인천",
  "대전",
  "대구",
  "부산",
  "광주/전라",
  "제주",
];
export const positionList: string[] = [
  "전체",
  "백엔드",
  "프론트엔드",
  "서버",
  "소프트웨어",
  "안드로이드",
  "iOS",
  "DevOps",
  "시스템/네트워크",
  "빅데이터",
];
export const conditionList: string[] = ["최신순", "추천순", "조회순"];

// 문제목록 조회 - 더미데이터
export const testData = [
  {
    problemId: 1,
    type: "answer",
    writer: "유저1",
    title: "제목입니다1",
    content:
      "Spring Boot의 장/단점 중 잘못된 것은 무엇인지 4가지 중에 골라주세요.",
    answer: "1",
    level: "bronze",
    tag: null,
    views: 275,
    likes: 79,
    createdTime: "2023-04-12T15:38:11.17258",
    hashTag: "CS,FrontEnd,BackEnd,Cloud",
  },
  {
    problemId: 1,
    type: "choice",
    writer: "유저2",
    title: "제목입니다2",
    content:
      "Spring Boot의 장/단점 중 잘못된 것은 무엇인지 4가지 중에 골라주세요.",
    answer: "",
    level: "silver",
    tag: null,
    views: 275,
    likes: 79,
    createdTime: "2023-04-12T15:38:11.17258",
    hashTag: "Cloud",
  },
  {
    problemId: 1,
    type: "choice",
    writer: "유저3",
    title: "제목입니다3",
    content:
      "Spring Boot의 장/단점 중 잘못된 것은 무엇인지 4가지 중에 골라주세요.",
    answer: "1",
    level: "gold",
    tag: null,
    views: 275,
    likes: 79,
    createdTime: "2023-04-12T15:38:11.17258",
    hashTag: "CS,Cloud",
  },
  {
    problemId: 1,
    type: "answer",
    writer: "유저1",
    title: "제목입니다4",
    content:
      "Spring Boot의 장/단점 중 잘못된 것은 무엇인지 4가지 중에 골라주세요.",
    answer: "",
    level: "bronze",
    tag: null,
    views: 275,
    likes: 79,
    createdTime: "2023-04-12T15:38:11.17258",
    hashTag: "Java",
  },
  {
    problemId: 1,
    type: "answer",
    writer: "유저1",
    title: "제목입니다5",
    content:
      "Spring Boot의 장/단점 중 잘못된 것은 무엇인지 4가지 중에 골라주세요.",
    answer: "1",
    level: "bronze",
    tag: null,
    views: 275,
    likes: 79,
    createdTime: "2023-04-12T15:38:11.17258",
    hashTag: "CS,FrontEnd,BackEnd,Cloud",
  },
  {
    problemId: 1,
    type: "answer",
    writer: "유저1",
    title: "제목입니다6",
    content:
      "Spring Boot의 장/단점 중 잘못된 것은 무엇인지 4가지 중에 골라주세요.",
    answer: "1",
    level: "bronze",
    tag: null,
    views: 275,
    likes: 79,
    createdTime: "2023-04-12T15:38:11.17258",
    hashTag: "CS,FrontEnd,BackEnd,Cloud",
  },
  {
    problemId: 1,
    type: "answer",
    writer: "유저1",
    title: "제목입니다7",
    content:
      "Spring Boot의 장/단점 중 잘못된 것은 무엇인지 4가지 중에 골라주세요.",
    answer: "1",
    level: "bronze",
    tag: null,
    views: 275,
    likes: 79,
    createdTime: "2023-04-12T15:38:11.17258",
    hashTag: "CS,FrontEnd,BackEnd,Cloud",
  },
  {
    problemId: 1,
    type: "answer",
    writer: "유저1",
    title: "제목입니다8",
    content:
      "Spring Boot의 장/단점 중 잘못된 것은 무엇인지 4가지 중에 골라주세요.",
    answer: "1",
    level: "bronze",
    tag: null,
    views: 275,
    likes: 79,
    createdTime: "2023-04-12T15:38:11.17258",
    hashTag: "CS,FrontEnd,BackEnd,Cloud",
  },
  {
    problemId: 1,
    type: "answer",
    writer: "유저1",
    title: "제목입니다9",
    content:
      "Spring Boot의 장/단점 중 잘못된 것은 무엇인지 4가지 중에 골라주세요.",
    answer: "1",
    level: "bronze",
    tag: null,
    views: 275,
    likes: 79,
    createdTime: "2023-04-12T15:38:11.17258",
    hashTag: "CS,FrontEnd,BackEnd,Cloud",
  },
  {
    problemId: 1,
    type: "answer",
    writer: "유저1",
    title: "제목입니다10",
    content:
      "Spring Boot의 장/단점 중 잘못된 것은 무엇인지 4가지 중에 골라주세요.",
    answer: "1",
    level: "bronze",
    tag: null,
    views: 275,
    likes: 79,
    createdTime: "2023-04-12T15:38:11.17258",
    hashTag: "CS,FrontEnd,BackEnd,Cloud",
  },
  {
    problemId: 1,
    type: "answer",
    writer: "유저11",
    title: "제목입니다11",
    content:
      "Spring Boot의 장/단점 중 잘못된 것은 무엇인지 4가지 중에 골라주세요.",
    answer: "1",
    level: "bronze",
    tag: null,
    views: 275,
    likes: 79,
    createdTime: "2023-04-12T15:38:11.17258",
    hashTag: "CS,FrontEnd,BackEnd,Cloud",
  },
  {
    problemId: 1,
    type: "answer",
    writer: "유저12",
    title: "제목입니다12",
    content:
      "Spring Boot의 장/단점 중 잘못된 것은 무엇인지 4가지 중에 골라주세요.",
    answer: "1",
    level: "bronze",
    tag: null,
    views: 275,
    likes: 79,
    createdTime: "2023-04-12T15:38:11.17258",
    hashTag: "CS,FrontEnd,BackEnd,Cloud",
  },
];
